set nocompatible                    " choose no compatibility with legacy vi
syntax enable
set encoding=utf-8
set showcmd                         " display incomplete commands
filetype plugin indent on           " load file type plugins + indentation
set number
set viminfo='10,\"100,:20,%,n~/.viminfo
set noswapfile
set laststatus=2

"" Whitespace
set nowrap                          " don't wrap lines
set tabstop=4 shiftwidth=4          " a tab is four spaces
set softtabstop=4
set expandtab                       " use spaces, not tabs (optional)
set backspace=indent,eol,start      " backspace through everything in insert mode

"" Searching
set hlsearch                        " highlight matches
set incsearch                       " incremental searching
set ignorecase                      " searches are case insensitive...
set smartcase                       " ... unless they contain at least one capital letter

"" Use ag if present
if executable('ag')
    " Note we extract the column as well as the file and line number
    set grepprg=ag\ --nogroup\ --nocolor\ --column
    set grepformat=%f:%l:%c%m
endif

"" Jump through results ith cursors
""nmap <silent> <RIGHT> :cnext<CR>
""nmap <silent> <LEFT> :cprev<CR>

"" Mouse scrolling
set mouse=a
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>

"" python specific settings
set autoindent

"" Load plugins
execute pathogen#infect()
call pathogen#helptags()

"" colours and syntax
set t_Co=16
let g:solarized_termcolors=256
set background=dark
colorscheme solarized

set clipboard=unnamed

nmap <F8> :TagbarToggle<CR>         " mapping f8 to TagbarToggle

command! -nargs=1 -complete=help H call HelpFullScreen( <f-args> )

function! HelpFullScreen( topic )
    exe "h " . a:topic
    wincmd j
    try
        clo
    catch /^Vim(\a\+):E444:/ " can't close last window
    endtry
endfunction
