---
# Custom config 

- hosts: all
  tasks:
    - name: Install mjolnir config
      copy: src=dotfiles/mjolnir/ dest=/Users/{{ ansible_user_id }}/.mjolnir/

    - name: Install git config
      copy: src=dotfiles/git/gitconfig dest=/Users/{{ ansible_user_id }}/.gitconfig

    - name: Install git ignore
      copy: src=dotfiles/git/gitignore_global dest=/Users/{{ ansible_user_id }}/.gitignore_global

      #- name: Install vimrc
      #copy: src=dotfiles/vimrc dest=/Users/{{ ansible_user_id }}/.vimrc

    - name: Ensure luarocks config dir
      file: path=/Users/{{ ansible_user_id }}/.luarocks/ state=directory

    - name: Configure luarocks for mjolnir
      copy: content='rocks_servers = { "http://rocks.moonscript.org" }' dest=/Users/{{ ansible_user_id }}/.luarocks/config.lua

    - name: Install mjolnir lua packages
      command: luarocks install {{ item }}
      with_items:
          - "mjolnir.hotkey"
          - "mjolnir.application"
          - "mjolnir.alert"
          - "mjolnir.sd.grid"
          - "mjolnir._asm.ui.notification"

    - name: Setup work project directory
      file: path=/Users/{{ ansible_user_id }}/projects state=directory
