---
- name: Install Dependencies
  apt:
    name={{item}}
    state=present
    update_cache=yes
  with_items: dependencies
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Install Dependencies
  homebrew:
    name={{item}}
    state=present
    update_homebrew=yes
  with_items: dependencies
  when: ansible_os_family == 'Darwin'

- name: Copy .vimrc
  copy: src=dotfiles/vimrc dest=/Users/{{ ansible_user_id }}/.vimrc
  #command: curl -LSso ~/.vimrc https://raw.github.com/ChengLong/configs/master/.vimrc
  #sudo: no

- name: Make directory for Pathogen
  file: path=~/.vim/autoload state=directory
  #command: mkdir -p ~/.vim/autoload ~/.vim/bundle

- name: Make directory for Pathogen
  file: path=~/.vim/bundle state=directory

- name: Install Pathogen
  get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim
  #command: curl -LSso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
  #sudo: no

- name: Install Solarized
  git:
    repo=git://github.com/altercation/vim-colors-solarized.git
    dest=~/.vim/bundle/vim-colors-solarized
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install Nerdtree
  git:
    repo=https://github.com/scrooloose/nerdtree.git
    dest=~/.vim/bundle/nerdtree
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install AutoComplPop
  git:
    repo=https://github.com/vim-scripts/AutoComplPop.git
    dest=~/.vim/bundle/AutoComplPop
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install vim-fugitive
  git:
    repo=https://github.com/tpope/vim-fugitive.git
    dest=~/.vim/bundle/vim-fugitive
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install CtrlP
  git:
    repo=https://github.com/kien/ctrlp.vim.git
    dest=~/.vim/bundle/ctrlp.vim
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install vim-better-whitespace
  git:
    repo=https://github.com/ntpeters/vim-better-whitespace.git
    dest=~/.vim/bundle/vim-better-whitespace
    update=yes
    accept_hostkey=yes
  sudo: no
