#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Make GNU coreutils apps my default
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

#export HOMEBREW_GITHUB_API_TOKEN=

# Aliases
alias ll='ls -lhaF'
alias rmpyc="find . -name '*.pyc' | xargs rm -fr"
alias ppjson='python -c "import simplejson; import sys; print simplejson.dumps(simplejson.loads(sys.stdin.read()), indent=4)" | pygmentize -f console -l js'
alias flushdns="sudo kill -HUP \$(ps -ef | grep mDNSResponder | grep -v grep | cut -d ' ' -f 8)"
alias afk="pmset displaysleepnow"
alias webserve="python -m SimpleHTTPServer 8000"
alias siftr="sift -r"

# For direnv
eval "$(direnv hook zsh)"

ghist () {
  CMD="history 0"
  for i; do
    CMD="$CMD | grep --color=always $i"
  done
  eval $CMD
}

source /usr/local/share/zsh/site-functions/_aws

# Enable shell command completion for gcloud.
source '/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
